### PR TITLE
fix(lang): typo in features word in russian docs

### PR DESCRIPTION
**Pull request by lamartire**

### CODE REVIEW

**Comment by damianopetrungaro** [comment]
Looks good to me!

@lamartire  if you want to you can contribute and update the russian documentation to the new versions!

**Comment by lamartire** [comment]
@damianopetrungaro no problem! You can mention me after release right in the pull request! 😸

**Comment by damianopetrungaro** [comment]
@lamartire we are actually 2 versions away from the latest Russian transaltion, so if you want you can already contribute ;)

**Comment by lamartire** [comment]
I'll find some time for it, promise 😉

**Pull request merged**
