### PR TITLE
feat(lang): add uzbek translation

### PR DESCRIPTION
**Pull request by softXengineer**

### CODE REVIEW

**Comment by softXengineer** [comment]
Hi @damianopetrungaro

Could you approve this PR?

**Comment by damianopetrungaro** [comment]
@softXengineer `1:32:38 PM: Error: "/opt/build/repo/config.yaml:422:1": failed to unmarshal YAML: yaml: line 422: mapping values are not allowed in this context` could you try running it locally? I suspect the `'` are the culprit there, maybe you could wrap it between `"`?

**Comment by softXengineer** [comment]
Hi @damianopetrungaro 

I've fixed the issue, you can check it out!

Thanks in advance

**Review by damianopetrungaro — APPROVED** [review]

**Comment by softXengineer** [comment]
Hi @stevemao!

Could you please provide some insights into the current status of the merge process and if there are any additional steps or information needed to move it forward? 

Thank you in advance!

**Comment by stevemao** [comment]
Thanks for your contributions!

**Pull request merged**
