### PR TITLE
add arabic translation

### PR DESCRIPTION
**Pull request by WatheqAlshowaiter**

### CODE REVIEW

**Comment by WatheqAlshowaiter** [comment]
hello @damianopetrungaro 

waiting to merge Arabic translation, or whoever responsible for the merge.

**Comment by damianopetrungaro** [comment]
I can see we already have a `ar` supported, but the older versions do not seem to be supported, if you want to upload the translation related to previous version can you rebase you PR and use the latest changes as well?

Thank you @WatheqAlshowaiter !

**Comment by WatheqAlshowaiter** [comment]
Thanks @damianopetrungaro 

The old translation is just an AI translation. Mine is real translation for the Arabic reader.. I will updated then pushed it again

**Comment by WatheqAlshowaiter** [comment]
@damianopetrungaro 

this is the updated version now

https://github.com/conventional-commits/conventionalcommits.org/pull/619

**Pull request closed without merging**
