### PR TITLE
docs(tooling): add several tools to the list

### PR DESCRIPTION
**Pull request by lucatrv**
Add the following tools for Conventional Commits:
- commitizen/cz-cli
- commitizen-tools/commitizen
- commitlint
- gitlint
- semantic-release

### CODE REVIEW

**Comment by bcoe** [comment]
@lucatrv I accidentally made this a merge conflict, bother you to rebase (sorry).

**Comment by lucatrv** [comment]
OK, I just rebased it on master.

**Comment by lucatrv** [comment]
@bcoe I rebased as requested... I hope I won't have to rebase again... :)

**Comment by damianopetrungaro** [comment]
Thanks @lucatrv !

**Pull request merged**
