### PR TITLE
docs(tooling): add python-semantic-release to the tooling list

### PR DESCRIPTION
**Pull request by lucatrv**

### CODE REVIEW

**Comment by damianopetrungaro** [comment]
@lucatrv the next version still has no ETA.
I'd suggest you add it to each language at its last version.
It is not a change to the convention itself :)

**Comment by lucatrv** [comment]
OK, I'll do in the next days, but then I think the following [phrase](https://github.com/conventional-commits/conventionalcommits.org#repo-layout) should be better detailed:

`./content/next/`: contains the version of the specification (where all the changes SHOULD be made).

**Comment by damianopetrungaro** [comment]
Should != Must :P

But if you want it's fine also to leave it on the next, but it won't be published soon :)

**Comment by lucatrv** [comment]
OK, clear... I'm gonna create a new PR.

**Comment by lucatrv** [comment]
I created PR #248. For now only in English as I do not have experience with the other languages...

**Pull request closed without merging**
