### PR TITLE
fix(faq): correct typo

### PR DESCRIPTION
**Pull request by vicrep**
Both are technically correct so might not be a typo, but IMO my suggestion is a clearer way to express this (putting the persona on the project/product as a whole, instead of on the developer).

### CODE REVIEW

**Comment by damianopetrungaro** [comment]
I ammnotna native speaker
@bcoe can help with this ;)

**Comment by damianopetrungaro** [comment]
@bcoe :ping:

**Comment by damianopetrungaro** [comment]
@vicrep  could you please resolve the conflicts?
After that we can :shipit:  :D

**Comment by vicrep** [comment]
Done @damianopetrungaro

**Comment by damianopetrungaro** [comment]
Thank you @vicrep !

**Pull request merged**
