### PR TITLE
fix: terminate types by a colon

### PR DESCRIPTION
**Pull request by smlx**

### CODE REVIEW

**Comment by damianopetrungaro** [comment]
Good catch! @bcoe anything to say about this?

**Comment by bcoe** [comment]
@smlx great catch, guess :shipit:

**Comment by bcoe** [comment]
@smlx could you fix this in the `beta.4` folder as well, which is currently the same as `next`.

**Comment by damianopetrungaro** [comment]
@smlx 🏓

**Comment by smlx** [comment]
> @smlx could you fix this in the `beta.4` folder as well, which is currently the same as `next`.

done!

**Comment by damianopetrungaro** [comment]
Thank you @smlx !

**Pull request merged**
