### PR TITLE
docs(tooling): add sv4git to tooling list

### PR DESCRIPTION
**Pull request by bvieira**
- add [sv4git](https://github.com/bvieira/sv4git)

### CODE REVIEW

**Comment by damianopetrungaro** [comment]
Could you add it to the next version as well @bvieira ?
Tag me so I can quickly merge this! (sorry for the delay, busy weeks)

**Comment by bvieira** [comment]
@damianopetrungaro 

> Could you add it to the next version as well @bvieira ?
> Tag me so I can quickly merge this! (sorry for the delay, busy weeks)

@damianopetrungaro next version is `content/next/index.md`, right?

**Comment by damianopetrungaro** [comment]
@bvieira exactly!

**Comment by bvieira** [comment]
> @bvieira exactly!

done!

**Pull request merged**
