### PR TITLE
style: reformat indent of collections and quotes in yaml file

### PR DESCRIPTION
**Pull request by ericyangpan**

### CODE REVIEW

**Comment by damianopetrungaro** [comment]
@arielyang what is the benefit?
It is a valid yaml file already :)

**Comment by arielyang** [comment]
> @arielyang what is the benefit?
> It is a valid yaml file already :)

There are different quotes in one file, some are single quotes, the others are double quotes.

**Comment by damianopetrungaro** [comment]
@stevemao it was already valid.
From the YAML specs:
```
- Whitespace indentation is used for denoting structure; however, tab characters are not allowed.
- Strings (scalars) are ordinarily unquoted, but may be enclosed in double-quotes ("), or single-quotes (').
```

But it's fine if we wanna standardize it (maybe we want to automate it?)

**Comment by damianopetrungaro** [comment]
@arielyang sorry for the late reply, can you fix the conflicts?
Ping me once it's done so I can merge it!

**Comment by damianopetrungaro** [comment]
@arielyang any update?

**Pull request closed without merging**
