### PR TITLE
Add summary button to welcome section

### LINKED ISSUE #131: Summary Button
On the landing page for Conventional Commits there are two buttons near the center of the page;  _Read the specs_ and _GitHub_. As demonstrated in #80, part of our community feels the summary plays a vital role in quickly on-boarding engineering organizations with the convention, and ensuring a high level of consistent adherence to the convention.

Could we further help teams by providing a button on the landing page that links to the _Summary_ instead of just the specification?

### PR DESCRIPTION
**Pull request by SimonKienzler**
If approved, fixes #131

I hope this is what you had in mind - if not, please let me know. First contribution here.

### CODE REVIEW

**Comment by damianopetrungaro** [comment]
Thank you so much for your contribution!
We may just need to update them in all the languages.
I can do the 🇮🇹  changes.
We need to ping other folks for the other languages.

**Comment by SimonKienzler** [comment]
@damianopetrungaro Is there anything for me to do? I assume "we" is the maintainers, and you're going to ping the translators?

**Comment by damianopetrungaro** [comment]
Yeah @SimonKienzler I need to ping them, I am gonna do it ASAP.
From your side looks good 👍 

Maybe @bcoe  and @hutson can help me.
I am super busy atm :)

**Comment by bcoe** [comment]
@SimonKienzler rather than blocking this PR, it would be helpful if you would create an issue:

"i18n: provide Quick Summary translations for other languages"

which references this PR, at which point I'd be happy to land this.

**Comment by bcoe** [comment]
@SimonKienzler thank you very much for the contribution.

**Pull request merged**
