### PR TITLE
:arrow_up: chore: added enforce-githooks tool to the list

### PR DESCRIPTION
**Pull request by Sulaiman-SM**
Hi guys,
As discusssed in issue #327 just added enforce-githooks tool to the list

### CODE REVIEW

**Comment by DeveloperC286** [comment]
Is the format of these commits generated by this tool not a violation of rule 1 of the specification? 

```
Commits MUST be prefixed with a type, which consists of a noun, feat, fix, etc ...
```

**Comment by Sulaiman-SM** [comment]
@DeveloperC286 all user commits should start with that convention however it will add an emojie based on the prefix type, and it will add it at the start of the message.
 sorry for the question but shouldn't we have such emojies in commit messages? should it be added it to the spec?

**Comment by DeveloperC286** [comment]
> @DeveloperC286 all user commits should start with that convention however it will add an emojie based on the prefix type, and it will add it at the start of the message.

There is no prefix type. However, there is a type which must be the prefix. My interpretation of the word prefix in the specification means at the very beginning of the commit, not after an emoji or anything else.

I am not a contributor or maintainer of the Conventional Commits specification, but I use the specification and have created tooling around it. None of my tools would be compatible with the commits generated by this tool. I would venture a guess and say, nor are most of the other tools built by others.

> sorry for the question but shouldn't we have such emojies in commit messages? should it be added it to the spec?

I have seen emoji used in the description and body of commits, and I think most linters accept that as valid. You will need confirmation from a maintainer if these commits generated are in violation. I suspect they are, in which case you could change the format from

```
:arrow_up: chore: added enforce-githooks tool to the list
```

to 

```
chore: :arrow_up: added enforce-githooks tool to the list 
```

**Comment by Sulaiman-SM** [comment]
@DeveloperC286 yes, I like your suggestion to move it after the colon, will wait for maintainers approval

**Pull request closed without merging**
