### PR TITLE
docs(v1.0.0): add v1.0.0 Spanish translation

### PR DESCRIPTION
**Pull request by ricguti**
Hi 👋 

Thank you for writing the specs of Conventional Commits. 

This PR adds the Spanish Translation of version v1.0.0.

Shout out to the people that translated to Spanish version 1.0.0-beta.2 as it was really helpful while translating version v1.0.0.

### CODE REVIEW

**Comment by damianopetrungaro** [comment]
@ricguti thanks for your time and sorry for my slow reply on this!

Do you have to update this with the latest change? (example removing the section at the end)

**Review by SSGoku369 — COMMENTED** [review]
ok

**Comment by SSGoku369** [comment]
ok

**Comment by ricguti** [comment]
@damianopetrungaro sorry for the late reply as well. I have time now and was about to continue with the Spanish translation but I see there's another pull request that was merge with it #414 😃 

So I think this PR could be closed as #414 does the same.

**Pull request closed without merging**
