### PR TITLE
docs: tidy "Conventional Commits" text references

### PR DESCRIPTION
**Pull request by lucatrv**

### CODE REVIEW

**Comment by bcoe** [comment]
👋 happy to land this, but thinking we should probably do this in the other languages too, and perhaps the next upcoming version?

**Comment by lucatrv** [comment]
@bcoe please see #241 discussion. I do not have experience with other languages, so I could make some damage. For instance in German sometimes it is called "Konventionelle Commits", and sometimes "konventionellen Commits", I have no idea which one is correct. As for `next`... let me know.

**Comment by lucatrv** [comment]
Please let me know if I need to do anything else.

**Comment by bcoe** [comment]
@lucatrv thank you for the contribution 👍

**Pull request merged**
