### PR TITLE
feat: Bump up beta version to 1.0.0-beta.3

### PR DESCRIPTION
**Pull request by damianopetrungaro**

### CODE REVIEW

**Comment by damianopetrungaro** [comment]
Could you please update the translations too?
@SimonDevelop  @doodlewind  @0x6368656174  @Morishiri  @archemiro 
😄 Let me know if you are free to do it!

**Comment by archemiro** [comment]
Great, very glad to see a new version! I can do the update for the Spanish translation, it might take a week or two, but I will be working on it.

**Comment by damianopetrungaro** [comment]
ty @archemiro !

**Comment by SimonDevelop** [comment]
@damianopetrungaro I think I have some time this weekend to do it :)

**Pull request merged**
