### PR TITLE
feat: Add `sh-conventional-commits` project

### PR DESCRIPTION
**Pull request by joaobsjunior**
Added shellscript project to the 'Tooling for Conventional Commits' list.

### CODE REVIEW

**Comment by joaobsjunior** [comment]
@ghermeto , how can we proceed with the PR?

**Review by henrikhelmers — APPROVED** [review]
LGTM

**Comment by joaobsjunior** [comment]
Hey @stevemao , how should we go about for PR reviews?

**Review by zeke — APPROVED** [review]
I haven't been actively involved in this project for a while, so I'm not sure what the current review process is, but this looks good to me. 👍🏼

**Comment by joaobsjunior** [comment]
@zeke, none of the maintainers are following the project anymore. Is the project abandoned? Can you approve this Pull Request?

**Pull request merged**
