### PR TITLE
docs: add example with commit scope and '!' breaking change

### PR DESCRIPTION
**Pull request by jdbruijn**
Please note that this is still missing the following translations due to lack in knowledge of those languages. I could use Google Translate to generate those, but I'd be unable to check and they'd likely contain incorrect structure or grammar. If that suffices I'd be happy to do just that, please let me know. I don't know what the process for this should be as I couldn't find anything on this in the contributing documents.

Callout to contributors/readers with knowledge of those translations, could you please add translation for the missing language(s) in the comments so I can add them to this PR?

Text to be translated:

```
Commit message with scope and `!` to draw attention to breaking change
```

Included translations.
- [x] index.de.md
- [x] index.fr.md
- [x] index.id.md
- [x] index.it.md
- [x] index.ja.md
- [x] index.ko.md
- [x] index.md
- [x] index.pt-br.md
- [x] index.ru.md
- [x] index.th.md
- [x] index.tr.md
- [x] index.uk.md
- [x] index.zh-hans.md
- [x] index.zh-hant.md

### CODE REVIEW

**Comment by damianopetrungaro** [comment]
I see there is already a `!`, next version release I 'll 🏓 all the maintainers, but good you spotted it a few months ago :D 

Gonna close this, @jdbruijn feel free to reopen if you have any follow up question/things to point out :D

**Comment by jdbruijn** [comment]
Maybe it's me but I don't see it, it being an example with `!` and a commit scope. I'm looking in this file https://github.com/conventional-commits/conventionalcommits.org/blob/cf1d0ae8e4df75055bcab505c37feaadc8b14d1f/content/next/index.md

If I'm missing it, could you please point to the location where that should be documented now?

**Comment by damianopetrungaro** [comment]
My bad, I misread the "with scope".

Sure we can ping language maintainers:
@bemnlam 
@DeronW 
@umutphp
@nimid 
@ygnoh  
@kmyk 
(@damianopetrungaro  me I'll take care of the 🇮🇹 one)

People, we need your help to add a tiny example, can you help us?

**Comment by umutphp** [comment]
Hi @damianopetrungaro ,

You can use the following text for Turkish translation.

```
refactor(runtime)!: Node 6 desteği kaldırıldı
```

**Comment by bemnlam** [comment]
@damianopetrungaro this is for `index.zh-hant.md`:

```
refactor(runtime)!: 不再支援 Node 6
```

**Comment by jdbruijn** [comment]
Thanks guys! Could you please translate the header as well (I've updated OP with what needs to be translated)?

**Comment by umutphp** [comment]
Hi @jdbruijn ,

Here is the header in Turkish;

```
Kapsamı belirtilen ve `!` ile yıkıcı değişikliğe dikkat çeken commit mesajı
```

**Comment by jdbruijn** [comment]
@damianopetrungaro Chinese traditional examples have the commit message in english, what do you want me to do here? Keep this one in English as well or this one in Chinese traditional as provided by @bemnlam ? In case of the latter I'd suggest creating a new ticket and PR for converting the other commit messages as well to keep it all the same.

**Comment by damianopetrungaro** [comment]
@jdbruijn 
Let's keep them as they are. No one complained so far.
If so we can manage that in another isssue&PR :)

**Comment by bemnlam** [comment]
@jdbruijn @damianopetrungaro I think we better keep all the commit messages the same (at least across Japanese, traditional Chinese and simplified Chinese). Please the following:

```
包含作用範圍和提示重大變更的 `!` 的提交說明

refactor(runtime)!: drop support for Node 6
```

**Comment by kmyk** [comment]
@damianopetrungaro @jdbruijn Please use this for `index.ja.md`

```
破壊的変更であることに気づいてもらうために `!` を付けて範囲のあるメッセージをコミットする

refactor(runtime)!: drop support for Node 6
```

**Review by umutphp — APPROVED** [review]

**Comment by damianopetrungaro** [comment]
@jdbruijn  🇮🇹 

```
## Messaggio di un commit con uno contesto e `!` per attirare attenzione ad una breaking change

refactor(runtime)!: drop support for Node 6
```

**Comment by jdbruijn** [comment]
@damianopetrungaro There is no Italian translation in v1.0.0 content, or am I missing something? Only waiting for Thai and Korean translation AFAIK.

**Comment by kmyk** [comment]
@jdbruijn  I've updated `index.ja.md` at #379. Other translated text in this file are updated, I would like to update the text of this pull request for the consistency.
Could you update it with the following (and resolve the merge conflict of #379)? Thank you!

```
スコープおよび破壊的変更を目立たせるための `!` を持つコミットメッセージ

refactor(runtime)!: drop support for Node 6
```

**Comment by bemnlam** [comment]
@damianopetrungaro @jdbruijn this is for `index.ko.md`:

```
단절적 변경(breaking change)에 주의를 주기위해 적용 범위(作用範圍)와 `!` 를 포함한 커밋 메세지

refactor(runtime)!: drop support for Node 6
```

got this translation with my friend's help.

**Comment by ygnoh** [comment]
@bemnlam 
I'm Korean. I think this is more natural:

> 단절적 변경(breaking change)에 주의를 주기 위해 적용 범위와 `!`를 포함한 커밋 메세지

Many Koreans don't understand `作用範圍`. That's Chinese.

**Comment by damianopetrungaro** [comment]
@jdbruijn Italian updated translation just added!

**Comment by jdbruijn** [comment]
Processed all comments (I think). Seems like some translations were added in the meantime or I missed them earlier. Updated OP with new list. Missing:
- Russian
- Thai
- Ukrainian
- Chinese Simplified

**Comment by nimid** [comment]
@damianopetrungaro @jdbruijn Please use this for index.th.md.

```
ข้อความ commit ที่ระบุขอบเขต และมี `!` เพื่อบ่งบอก breaking change

refactor(runtime)!: drop support for Node 6
```

**Comment by DeronW** [comment]
hi @jdbruijn  @damianopetrungaro  this is for `index.zh-hans.md`:

> 包含了范围和破坏性变更 `!` 的提交說明
> 
> refactor(runtime)!: drop support for Node 6

**Review by bcoe — APPROVED** [review]

**Comment by bcoe** [comment]
this looks good to me, @damianopetrungaro shall we land, and update other translations later?

**Comment by jdbruijn** [comment]
I'll push the Thai and Chinese translations in a bit! Then only Russian and Ukrainian are remaining.

**Comment by jdbruijn** [comment]
Done!

**Comment by jdbruijn** [comment]
Added Ukrainian translation, translated by a colleague of mine. He also told me that "контекст" is a better translation for "scope". I can't make sense of the writing so I'll leave that up to the other maintainers/translators to handle separately from this PR. If wanted I can make an issue for that though.

**Comment by rakovets** [comment]
@jdbruijn 🇷🇺

```
## Сообщение коммита с _контекстом_ и `!` для привлечения внимания к `BREAKING CHANGE`

refactor(runtime)!: drop support for Node 6
```

I use `_контекстом_`, ``` `BREAKING CHANGE` ``` because this is the style that the first author used for the Russian translation.

**Comment by jdbruijn** [comment]
Okay, we're actually complete now. All translations are added, with a big thanks to all translators!

@damianopetrungaro as far as I'm concerned this can be merged now.

**Review by bcoe — APPROVED** [review]

**Comment by bcoe** [comment]
@jdbruijn thanks for the contribution 👌

**Pull request merged**
