### PR TITLE
docs: Add GearLock in projects list

### PR DESCRIPTION
**Pull request by axonasif**
CC was the kind of thing I've been always looking for, glad I found it.
Now I no longer have to struggle with changelog generation and version bumping with a custom solution for my project.

### CODE REVIEW

**Review by damianopetrungaro — APPROVED** [review]

**Comment by damianopetrungaro** [comment]
There are some conflicts @axonasif !
I think we move all of those links to the about page, if you move them there I will approve it next week!

Sorry for the delay, I missed this PR!

**Comment by bcoe** [comment]
@axonasif friendly nudge, regarding resolving conflicts.

**Comment by axonasif** [comment]
Thanks for getting back on this 🙏

**Comment by damianopetrungaro** [comment]
@axonasif thanks for the changes, I think you're still missing updating the `https://github.com/conventional-commits/conventionalcommits.org/tree/master/content/about` page :D

**Comment by axonasif** [comment]
Done! Please feel free to squash this PR while merging 🙏

**Review by damianopetrungaro — APPROVED** [review]

**Pull request merged**
