### PR TITLE
feat(lang): Add Indonesian (ID) translation for version v1.0.0

### PR DESCRIPTION
**Pull request by aldinp16**

### CODE REVIEW

**Comment by damianopetrungaro** [comment]
Only one thing missing!
You need to add it [there](https://github.com/conventional-commits/conventionalcommits.org/blob/master/config.yaml) too

**Comment by damianopetrungaro** [comment]
@aldinp16 Could you fix the conflicts?
So we can merge it :D 
Please ping me back when you're done otherwise we'll have no idea that it is ready ;)

**Comment by aldinp16** [comment]
Ok, thank you. There are no big changes that I make. I only change some terms like body, scope etc. instead of using "Badan", "Cakupan" etc. because that would be confusing.

**Comment by bcoe** [comment]
@aldinp16 @damianopetrungaro is this good to go?

**Comment by damianopetrungaro** [comment]
Thanks @aldinp16!

**Pull request merged**
