### PR TITLE
Armenian Translation

### PR DESCRIPTION
**Pull request by lanycrost**
This is Armenian translation for Conventional Commits 1.0.0-beta.4 and 1.0.0-beta.3

### CODE REVIEW

**Comment by bcoe** [comment]
see: https://github.com/conventional-commits/conventionalcommits.org/pull/185, working on a few tweaks to help eliminate parsing ambiguities, and move us towards V1 of the spec.

**Comment by lanycrost** [comment]
@bcoe OK, I follow. I can create PR after all reviewers have accepted the changes :smile:

**Comment by damianopetrungaro** [comment]
Before we merge it we need to fix some CSS in order to avoid text overlap.
@lorenzodianni can you take care of it?

**Comment by lorenzodianni** [comment]
@damianopetrungaro I'll work on this week 💪

**Comment by damianopetrungaro** [comment]
Great!
Thanks!

**Comment by lorenzodianni** [comment]
It's ready in #188 🔥 
@damianopetrungaro

**Pull request merged**
