### PR TITLE
feat(lang): add russian translation for v1.0.0-beta.3

### PR DESCRIPTION
**Pull request by lamartire**

### CODE REVIEW

**Comment by damianopetrungaro** [comment]
Could you add the versions available in the config.yml (under the Russian section)?

**Comment by lamartire** [comment]
@damianopetrungaro oh, sure.

**Comment by lamartire** [comment]
@damianopetrungaro all done!

**Comment by damianopetrungaro** [comment]
Perfect @lamartire ! Looks amazing!

**Comment by lamartire** [comment]
Thank you, mate 🙂

**Pull request merged**
