### PR TITLE
ui: move about to another page

### PR DESCRIPTION
**Pull request by damianopetrungaro**
I noticed that most of the languages did not update the translations regarding the "About" section with all the tools and projects.

Since the list is growing as well, and maintaining future translation for that will cost a lot, I decided to create a new section "About" with all those information.

### CODE REVIEW

**Comment by damianopetrungaro** [comment]
@bcoe let me know what you think about that 😄

**Comment by bcoe** [comment]
@damianopetrungaro I like this idea, but wondering if we should take it further and have:

`[Background]` and `[Tools]`

Then we can flesh out background a little bit more without translating it, give a timeline of when Angular proposed the convention, when this spec was written.

**Comment by damianopetrungaro** [comment]
@bcoe  you mean on the "About" page or you mean more having 2 more pages to add to the nav-header as well?

**Comment by bcoe** [comment]
@damianopetrungaro I was thinking just two pages, no `About`.

About is kind of generic, and really the type of information we include in "About" is some background on who wrote who came up with the idea initially, who wrote the draft, etc -- which sounds to me more like "Background".

Then we have a big list of "Tools" folks have written.

**Review by bcoe — APPROVED** [review]

**Pull request merged**
