### PR TITLE
fix(zh): improve translation of scope

### PR DESCRIPTION
**Pull request by Artoria2e5**
Scope should not be translated in the programming sense.

### CODE REVIEW

**Comment by bcoe** [comment]
@Artoria2e5 bother you to update to the newly landed `1.0.0`?

**Comment by Artoria2e5** [comment]
wow it's out of beta now?! sure soon damn yeah

**Comment by bcoe** [comment]
@Artoria2e5 bother you to dust off this PR?

**Comment by damianopetrungaro** [comment]
Hey @Artoria2e5 could you please resolve the conflicts?

**Comment by damianopetrungaro** [comment]
I am gonna close this one due to inactivity, since also the `zh` translation has been split into two different pages it may not be needed anymore.
If you want @Artoria2e5 feel free to reopen the PR!!

**Pull request closed without merging**
