### PR TITLE
Russian translation added

### PR DESCRIPTION
**Pull request by 0x6368656174**
If you add me to the contributors, I will follow the current Russian translation.

### CODE REVIEW

**Comment by 0x6368656174** [comment]
@stevemao I do not have access to @conventional-commits/committee

**Comment by damianopetrungaro** [comment]
@stevemao  the committee is usually for people who show interest to the specs and keep improving it :D

**Comment by damianopetrungaro** [comment]
btw I really like the PR! I am gonna merge it!
@0x6368656174 ty very much for the effort! 
Hope to see you active in the specs and add you to the committee 😄

**Comment by 0x6368656174** [comment]
@damianopetrungaro  The specification is good and useful for the community, I would love to support its Russian translation. Just without recording rights is inconvenient. You published a PR, I found mistakes in it, and in order to correct it, I need to create a new PR with minor edits, after which the merge distracts you from it.

**Comment by damianopetrungaro** [comment]
I didn't get it
> Just without recording rights is inconvenient. You published a PR, I found mistakes in it, and in order to correct it, I need to create a new PR with minor edits, after which the merge distracts you from it.

**Pull request merged**
