### PR TITLE
docs: add @tandil/diffparse and @tandil/diffsplit to project list

### PR DESCRIPTION
**Pull request by danielduarte**

### CODE REVIEW

**Comment by damianopetrungaro** [comment]
Thanks @danielduarte !

**Comment by SirWindfield** [comment]
Did the merge result in https://www.conventionalcommits.org/en/v1.0.0 being unreachable for a new upload of the spec?

**Comment by damianopetrungaro** [comment]
Checking 👀

**Comment by damianopetrungaro** [comment]
@SirWindfield I think it just a cache CI related issue, now it's cool!

**Comment by SirWindfield** [comment]
Hm doesn't work on my side though, opening https://www.conventionalcommits.org/ redirects to https://www.conventionalcommits.org/en/v1.0.0-beta.4/.

**Comment by danielduarte** [comment]
The redirect is fixed now @SirWindfield.
Now it redirects properly to https://www.conventionalcommits.org/en/v1.0.0/ :+1:

**Pull request merged**
