### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by Zearin**
docs(spec): Minor copy edits to capitalization, phrasing, punctuation, and formatting.

Edit goals:

- No edits should change the meaning of the edited text
- Consistency of punctuation for repeated phrases (e.g., all “e.g.” statements in parentheses like this)
- Consistency of capital letters for each description in the lists of links at the end of the document
- Consistency of formatting inline examples (e.g., always format example commits with `backticks`, rather than mixing `backticks` and _italics_)

A few other minor copy edits are totally subjective, and (hopefully) provide some subtle aesthetic improvement.  (Or, at least, go unnoticed. That’s okay, too. :-) )

### CODE REVIEW

**Review by adonyssantos — APPROVED** [review]

**Comment by Zearin** [comment]
@damianopetrungaro ping :)  

Good to merge?

**Comment by damianopetrungaro** [comment]
@bcoe you're better than me for this PR :) 
Let me know if that looks good and I can merge it!

**Comment by bcoe** [comment]
👋 sorry for the very slow turn around, up for rebasing @Zearin?

I think probably we should make these changes in `next` and then call this a patch release of conventional-commits, since it changes language around a bit.

**Comment by damianopetrungaro** [comment]
Closing as inactive, @Zearin  feel free to propose this again if you find that relevant!

**Pull request closed without merging**
