### PR TITLE
fix: gitignore file has been fixed

### PR DESCRIPTION
**Pull request by didaquis**
* Fixed URL on `.gitignore` related to CSS and JS auto generated 
* Removed unnecessary rules from `.gitignore`

### CODE REVIEW

**Comment by damianopetrungaro** [comment]
@didaquis why do you want to delete the `themes/conventional-commits/package-lock.json` as well?

**Comment by didaquis** [comment]
Hi. I figured that file was not wanted in the repository since in the "gitignore" file it was already excluding when I created this PR. 

If you prefer the "package-lock.json" file to be included in the repository, let me know. I will then edit the PR to restore it and remove the exclusion of the "gitignore" file that was previously there.

**Comment by damianopetrungaro** [comment]
I'd keep it in order to maintain vendor locking in more safely @didaquis , AFAIK in the JS world locking is guaranteed only on direct deps of a project not including the deps of deps in `package.json`.

**Comment by didaquis** [comment]
Hi @damianopetrungaro, what do you think now?  🙂

**Comment by damianopetrungaro** [comment]
Thanks @didaquis

**Pull request merged**
