### PR TITLE
fix!: replacing 'feat' with 'feature'

### LINKED ISSUE #200: should "feature" be alias for "feat"
A few folks have pointed out that "feat" can be confusing, is adding ambiguity worth saving three characters?

CC: @jskeet, and @bshaffer, who brought this up.

### PR DESCRIPTION
**Pull request by Shchvova**
BREAKING CHANGE
Many noted that 'feat' seems like very unnatural abbreviation saving only 3 symbols while ruining aesthetics by replacing one word with another one, which is completely out of context.

closes #200

### CODE REVIEW

**Comment by Shchvova** [comment]
Relevant discussion on https://news.ycombinator.com/item?id=21125669

**Comment by bcoe** [comment]
@Shchvova similar to how we indicate `Breaking-Change:` can be used instead of `Breaking Change`, I'd like to introduce `feature:` as an optional alternative that parsers parse:

1. some folks do like to save characters, if they're trying to keep to a `52` character title (and don't mind the abbreviation).
2. it means we don't break all of the existing tooling and habits as we deploy this updated recommendation.

I suggest we go with @tunnckoCore's recommendation of adding a sub-bullet to the pertinent entry:

```
1. The type `feat` MUST be used when a commit adds a new feature to your application or library.
  1. The type `feature` MAY be used as an alternative, and MUST be supported by tooling.
```

While you're at it, if you feel like moving the `BREAKING-CHANGE` alternative under a bullet, would greatly appreciate it.

**Comment by Shchvova** [comment]
This indeed sounds great. I'll try to get changes in if I can figure out Github

Honestly, I like abbreviations. But saving just 4 symbols won't do a difference.

**Comment by damianopetrungaro** [comment]
Do we want to introduce BC?
IMHO this can be supported with `feat` too.
So we just bump it to 1.1.0 ;) 

@bcoe

**Comment by tunnckoCore** [comment]
I don't see how this can be breaking change. It's adding of sub-bullet which introduce optional "rule" - MAY.

**Comment by tunnckoCore** [comment]
Yea, I've felt that :D I was talking about @bcoe suggestion. Which is best. 

In general, I think the spec shouldn't mess with that et al. Or at least should only touch in the way @bcoe suggested.
 Tools should be smart enough to assume that "feature" is obviously a possibility, and thus support it.

**Comment by bcoe** [comment]
@Shchvova is this still something you would like to land, mind addressing the suggestions?

**Comment by Shchvova** [comment]
I like the suggestion here.

**Comment by poppahorse** [comment]
Just had to rewrite my commit messages as I'm an idiot and forgot its `feat` and not `feature`.

In case it helps anyone:

```git filter-branch --msg-filter 'sed "s/feature:/feat:/g"'```

**Comment by damianopetrungaro** [comment]
@poppahorse you can still support your own type tho, so there was no need to change it :)

**Comment by damianopetrungaro** [comment]
Closing due to inactivity, @Shchvova  please feel free to reopen if you think it is still needed

**Pull request closed without merging**
