### PR TITLE
docs: add Change to tooling section

### PR DESCRIPTION
**Pull request by adamtabrams**

### CODE REVIEW

**Comment by damianopetrungaro** [comment]
Hey @adamtabrams sorry for the late reply, could you please rebase your branch?
Feel free to @ me when you're done so I can merge it : D

**Comment by damianopetrungaro** [comment]
(also, add it to the next version as well, so we won't' skip it :D)

**Review by tunnckoCore — APPROVED** [review]
sweet!

**Comment by tunnckoCore** [comment]
@adamtabrams does it "autlinks" the references and commits? 

It would be awesome if the template is like

```

## Added

- commit hash - title (with linked issues/references)
```

**Comment by adamtabrams** [comment]
> @adamtabrams does it "autlinks" the references and commits?
> 
> It would be awesome if the template is like
> 
> ```
> 
> ## Added
> 
> - commit hash - this fixes #123 (with linked issues/references)
> ```

@tunnckoCore Not yet, but that does sound like a great feature! You should consider about making a PR for something like that or even just adding an issue for it.

**Comment by adamtabrams** [comment]
@damianopetrungaro Everything should be up to date now.

**Pull request merged**
